name: CI Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercased repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ env.REPO_OWNER_LC}}/medical-frontend
          docker build --build-arg REACT_APP_API_BASE_URL=https://kumiko.pro \
                       -t $IMAGE:sha-${{ github.sha }} .
          docker push $IMAGE:sha-${{ github.sha }}

  update-infra:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Set lowercased repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Clone infra repo
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/dan6103605/infra.git
          cd infra
          git config user.email "ci@github"
          git config user.name "GitHub Actions"

          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/${{ env.REPO_OWNER_LC}}/medical-frontend:sha-${{ github.sha }}"' apps/frontend/device/deployment.yaml

          git add apps/frontend/device/deployment.yaml
          git commit -m "Update medical-frontend image to sha-${{ github.sha }}"
          git push origin main
